services:
  postgres:
    image: postgres:17-alpine
    container_name: fitpulse-postgres
    environment:
      POSTGRES_DB: fitpulse
      POSTGRES_USER: fitpulse
      POSTGRES_PASSWORD: fitpulse
    ports:
      - "5432:5432"
    volumes:
      - fitpulse-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitpulse -d fitpulse"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: fitpulse-mongo
    ports:
      - "27017:27017"
    volumes:
      - fitpulse-mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: fitpulse-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitpulse-api
    ports:
      - "5180:5180" # REST + GraphQL
      - "5181:5181" # gRPC
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgresConnection: "Host=postgres;Port=5432;Database=fitpulse;Username=fitpulse;Password=fitpulse"
      MongoSettings__ConnectionString: "mongodb://mongo:27017"
      MongoSettings__DatabaseName: "fitpulse"
      Smtp__Host: "mailhog"
      Smtp__Port: "1025"
      Smtp__FromAddress: "noreply@fitpulse.be"
      Auth0__Domain: "dev-h87kqnvmjii25c7l.us.auth0.com"
      Auth0__Audience: "https://fitpulse.api"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mailhog:
        condition: service_started

volumes:
  fitpulse-postgres-data:
  fitpulse-mongo-data:
